### ISSUE TITLE
Optionale Elemente in finanzierungsObjektDetails sind erforderlich.

### ISSUE THREAD

**Issue by HaukeJensen** [hypoport/europace2-api#1]
<?xml version="1.0" encoding="UTF-8"?>

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    SOAP-ENV:Header
        <LoggingId xmlns="www.europace2.de/baufiSmart/bex/schema/bex-v10-VorgangAnlegen">xx</LoggingId>
    /SOAP-ENV:Header
    SOAP-ENV:Body
        SOAP-ENV:Fault
            <faultcode>SOAP-ENV:Client</faultcode>
            <faultstring>No signature of method: de.hypoport.ep2.baufismart.bex.backend.service.mapper.domaintypen.immobilie.BexImmobilienDetailsMapperImpl.map*() is applicable for argument types: (groovy.util.slurpersupport.NoChildren, java.lang.String, groovy.json.JsonBuilder) values: [, , null]
Possible solutions: wait(), any(), map(de.hypoport.ep2.baufismart.bex.backend.service.mapper.domaintypen.immobilie.ObjektDetailsMitGrundstuecksGroesse), find(), grep(), dump()</faultstring>
        /SOAP-ENV:Fault
    /SOAP-ENV:Body
/SOAP-ENV:Envelope

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="www.europace2.de/baufiSmart/bex/schema/bex-v10-VorgangAnlegen">
    SOAP-ENV:Header
        ns1:LoggingIdxx/ns1:LoggingId
        ns1:DatenKontextTEST_MODUS/ns1:DatenKontext
        ns1:EmpfaengerPartnerIdxxxxx/ns1:EmpfaengerPartnerId
        ns1:BearbeiterPartnerIdxxxxx/ns1:BearbeiterPartnerId
        ns1:ApiKeyxxxxxxxxxxxxxxx/ns1:ApiKey
    /SOAP-ENV:Header
    SOAP-ENV:Body
        ns1:Vorgang
            <erfassteDaten>
                <antragsteller>
                    <anrede>FRAU</anrede>
                    <beschaeftigung>
                        <angestellterOderArbeiterOderBeamter>
                            <arbeitgeberInDeutschland>TRUE</arbeitgeberInDeutschland>
                            <beschaeftigtSeit>2010-01-01</beschaeftigtSeit>
                            <einkommenNettoMonatlich>245</einkommenNettoMonatlich>
                            <inProbezeit>FALSE</inProbezeit>
                            <typ>ANGESTELLTER</typ>
                        </angestellterOderArbeiterOderBeamter>
                    </beschaeftigung>
                    <email>test@test.de</email>
                    <externeAntragstellerId>1448540659_11000113</externeAntragstellerId>
                    <familienstand>LEDIG</familienstand>
                    <geburtsdatum>1990-01-01</geburtsdatum>
                    <guetertrennungVereinbartWennVerheiratet>FALSE</guetertrennungVereinbartWennVerheiratet>
                    <nachname>test</nachname>
                    <staatsangehoerigkeit>DE</staatsangehoerigkeit>
                    <titelDoktor>FALSE</titelDoktor>
                    <titelProfessor>FALSE</titelProfessor>
                    <verheiratetmitWeiteremAntragsteller>FALSE</verheiratetmitWeiteremAntragsteller>
                    <vorname>test</vorname>
                    <wohnhaftSeit>2000-01-01</wohnhaftSeit>
                </antragsteller>
                <haushalt>
                    <bestehendeImmobilien/>
                </haushalt>
                <finanzierungsObjekt>
                    <autoStellplaetze>
                        <autoStellPlatz>
                            <typ>GARAGE</typ>
                        </autoStellPlatz>
                    </autoStellplaetze>
                    <erbbaurecht>
                        <erbbaurechtVorhanden>FALSE</erbbaurechtVorhanden>
                    </erbbaurecht>
                    <externeImmobilienId>49</externeImmobilienId>
                    <finanzierungsObjektDetails/>
                </finanzierungsObjekt>
                <vorhaben>
                    <eigenleistungWennNeubauOderModernisierungsmassnahmen>3456</eigenleistungWennNeubauOderModernisierungsmassnahmen>
                    <finanzierungsWunsch>
                        <annuitaetenOderForwardDarlehen>
                            <tilgungsWunsch/>
                            <bereitstellungsZinsfreieZeitInMonaten>2345</bereitstellungsZinsfreieZeitInMonaten>
                            <darlehensBetrag>2345</darlehensBetrag>
                            <sondertilgungOptionalJaehrlich>2345</sondertilgungOptionalJaehrlich>
                            <typ>FORWARDDARLEHEN</typ>
                            <zinsbindungInJahren>10</zinsbindungInJahren>
                        </annuitaetenOderForwardDarlehen>
                        <privatDarlehen>
                            <darlehensBetrag>1345</darlehensBetrag>
                            <laufzeitInMonaten>180</laufzeitInMonaten>
                        </privatDarlehen>
                        <zwischenFinanzierung>
                            <darlehensBetrag>2345</darlehensBetrag>
                            <maximaleLaufzeitInMonaten>24</maximaleLaufzeitInMonaten>
                        </zwischenFinanzierung>
                    </finanzierungsWunsch>
                    <verwendungszweck>ANSCHLUSSFINANZIERUNG</verwendungszweck>
                    <verwendungszweckAbhaengigerFinanzbedarf>
                        <anschlussfinanzierung>
                            <zusaetzlichesKapital>2456</zusaetzlichesKapital>
                        </anschlussfinanzierung>
                    </verwendungszweckAbhaengigerFinanzbedarf>
                </vorhaben>
            </erfassteDaten>
        /ns1:Vorgang
    /SOAP-ENV:Body
/SOAP-ENV:Envelope

**Comment by joerg-pfruender-hp** [comment]
Thank you for reporting. I'll work on it next week.

**Comment by joerg-pfruender-hp** [comment]
The issue is fixed.

**Comment by Atrusberlin** [comment]
Close, already fixed.
