### ISSUE TITLE
Art der Beschäftigung

### ISSUE THREAD

**Issue by isk0001y** [hypoport/europace2-api#10]
Hallo,

Wird in Zukunft die Art der Beschäftigung evtl. doch ein Enum?

**Comment by ollio** [comment]
Wie viele Konstanten, können Sie auch die Art der Beschäftigung behandeln. Die Werte verhalten sich wie ein Enum. Wenn wir bei diesen Werten ein echtes Enum nehmen, dann würde jede neue Beschäftigungsart zu einem Bruch der Api führen, da der Client den neuen Enum Wert nicht auflösen kann. Wir wären gezwungen viele neue API Versionen zu releasen und die Clients müssten sich aktualisieren. 
Daher haben wir den deskriptiven Ansatz gewählt.
