### ISSUE TITLE
BestehendesDarlehen

### ISSUE THREAD

**Issue by isk0001y** [hypoport/europace2-api#11]
Hallo,

Die Art des bestehenden Darlehens sowie die unterschiedlichen Darlehensgebertypen sind mir in der Vorgang-Auslesen API ein wenig unklar. Wie werden diese genauer übermittelt?

**Comment by ptrsauer** [comment]
Bestehende Darlehen sind Darlehen, welche bei einer Prolongation oder Umschuldung abgelöst werden sollen. Sofern bekannt, wird der entsprechende Produktanbieter als Darlehensgeber ausgegeben.

Für das Feld darlehensArt sind folgende Werte mit den entsprechenden Bedeutungen zulässig: BAUSPARDARLEHEN, FOERDERDARLEHEN, IMMOBILIENDARLEHEN, SONSTIGES_DARLEHEN.

Hilft Ihnen das weiter?

**Comment by ptrsauer** [comment]
Ich nehme an, dass Ihnen die Antwort geholfen hat. Falls Sie noch weitere Fragen diesbezüglich haben, können Sie das Issue wieder auf machen oder ein neues Anlegen.
