### ISSUE TITLE
Allgemeine Frage bzgl. VorgangAuslesen API status

### ISSUE THREAD

**Issue by isk0001y** [hypoport/europace2-api#12]
Hallo,

Ich arbeite derzeit an einen mapper, der die ausgelesenen Daten in unser Datenmodell konvertieren soll. Bisher haben wir erfassteDaten aus dem Subbaum bei einem Angebot verwendet.

Es ist aber so, dass viele verschiedene Informationen im neuen Datenmodell so gar nicht vorhanden sind, die ich jetzt nicht auflisten will. Aber dazu reicht einfach die Felder zu vergleichen bei gleich benannten Objekten wie BestehendesDarlehen.

Die Frage ist nun, ob das alles nachgeholt sein wird, oder nicht?

**Comment by isk0001y** [comment]
Wieso sind bei einigen Darlehenswünschen die Dauer-Attribute in Jahren, in anderen in Monaten angegeben?

**Comment by isk0001y** [comment]
Es scheint zwei Schreibweisen für Verwendungszweck zu geben:
Vorhaben.VerwendungszweckEnum
ZwischenFinanzierungsWunsch.VerwendungsZweckEnum

**Comment by ptrsauer** [comment]
Hallo,

mittelfristig werden alle Informationen aus der Plattform auch über die Vorgänge API verfügbar sein. Also ja, die bisher noch fehlenden Felder werden nachgeholt.

Bezüglich der Dauer der Darlehenswünsche: Bei einigen Darlehen ergibt eine Angabe in Jahren Sinn. So zum Beispiel beim Annuitätendarlehen. Andere Darlehensarten, wie zum Beispiel die Zwischenfinanzierung, werden eher in Monaten angegeben. Daher ist beides möglich.

Die unterschiedliche Schreibweise für den Verwendungszweck ist so nicht gewollt und gilt es zu beheben. Diesbezüglich würde es uns helfen, wenn Sie zukünftig für unterschiedliche Fragen/Anregungen/Wünsche/Fehlermeldungen separate Issues anlegen. Dann können wir diese strukturierter bearbeiten.

**Comment by ptrsauer** [comment]
Die Schreibweise für Verwendungszweck wurde jetzt vereinheitlicht.
