### ISSUE TITLE
VorgangAuslesen-API: maklergebuehr fehlt

### ISSUE THREAD

**Issue by ic-hv** [hypoport/europace2-api#13]
Beim Auslesen eines Vorgangs sollte normalerweise im Feld vorhaben / finanzbedarf / maklergebuehr die Maklergebühr ausgegeben werden, die für das Vorhaben in Europace hinterlegt wurde. Bei meinen Tests wurde dieses Feld allerdings nicht ausgeliefert, obwohl ein Wert via Europace hinterlegt ist.

**Comment by ollio** [comment]
Wir haben uns überlegt, Maklergebühren, Provisionen, Overheads etc. in einer eigenen API zur Verfügung zu stellen, da der Context ein anderer ist. Sowie wir diese API umsetzen, werden wir das Thema aufgreifen.

**Comment by ollio** [comment]
Die Maklergebühr sollte im Finanzbedarf enthalten sein, wenn diese erfasst wurde.

**Comment by ic-hv** [comment]
Ist sie aber nicht - die Grunderwerbssteuer und die Notargebuehr fehlen wohl auch ... siehe Screenshots ...
![europace](https://cloud.githubusercontent.com/assets/26538616/25215891/5a91943a-25a0-11e7-9904-906234149bb2.png)
![api](https://cloud.githubusercontent.com/assets/26538616/25215894/5ab4e9e4-25a0-11e7-96b9-46c6566f9e5a.png)
Die Debugger-View zeigt die unmodifizierten JSON-Daten, die ich von der Schnittstelle erhalte ... es handelt sich um Echtdaten, also kein Mock. Es ist zu sehen, das keine Angaben zu Grunderwerbssteuer, Makler- und  Notargebuehr vorhanden sind.

**Comment by ptrsauer** [comment]
Das Problem wurde jetzt behoben. Vielen Dank für das Melden des Problems!
