### ISSUE TITLE
Vorgänge auslesen per Zeitstempel - Sortierung der Vorgänge - Probleme zwischen Pages

### ISSUE THREAD

**Issue by ic-hv** [hypoport/europace2-api#15]
Beim Auslesen sämtlicher Vorgänge via REST-API ist mir ein unschöner Umstand aufgefallen, der meiner Meinung nach behoben werden sollte. 

Normalerweise wird ja nur eine vorgegebene Anzahl von Vorgängen ausgelesen und mit dem page-Parameter können weitere Vorgänge nachgeladen werden. Innerhalb einer Page sind die Vorgänge allesamt schön chronologisch nach dem Zeitstempel der letzten Änderung aufsteigend sortiert. Allerdings nicht fortlaufend zwischen zwei Pages - d.h es kann sein, das das letze Änderungsdatum eines Vorgangs auf einer nachfolgenden Page plötzlich kleiner ist als das Änderungsdatums des letzten Vorgangseintrags auf der Paga davor. 

Liesse sich das bitte ändern? D.h. das Vorgänge auch über sämtliche Pages hinweg chronologisch ausgeliefert werden?

**Comment by ptrsauer** [comment]
Ok. Das sollte auf jeden Fall nicht so sein. Wir schauen uns da an und werden es fixen.

**Comment by ptrsauer** [comment]
Ich konnte das beschriebene Verhalten reproduzieren. Es handelt sich definitiv um einen Fehler. Vielen Dank schon mal für den Hinweis!

**Comment by ptrsauer** [comment]
Ich habe hierzu einen Fix deployed und wir beobachten morgen die Performance dieser Funktionalität.

**Comment by ptrsauer** [comment]
Die Performance passt unsererseits. Vielen Dank für die Info!
