### ISSUE TITLE
Zeitstempel der letzten Änderung wird nicht in jedem Fall geupdatet

### ISSUE THREAD

**Issue by ic-hv** [hypoport/europace2-api#16]
Habe gerade festgestellt, das wenn ich beispielsweise nur den Kaufpreis eines Objekts via Vorhaben-Tab in der Europace GUI ändere und anschliessend via REST-API den Vorgang auslese dann hat sich zwar der Kaufpreis entsprechend geändert, allerdings ist der Zeitpunkt der letzten Änderung unverändert.

**Comment by ptrsauer** [comment]
Bei dem Zeitstempel handelt es sich um den Zeitpunkt des letzten Ereignisses. Es wird nicht bei jeder Änderung ein Ereignis erzeugt. Ereignisse sind in GUI in der Ereignis-Lasche zu sehen:
<img width="324" alt="bildschirmfoto 2017-06-06 um 22 57 23" src="https://user-images.githubusercontent.com/13761565/26851595-953c0a3a-4b0b-11e7-8250-0d0cdf17c4ae.png">

**Comment by ic-hv** [comment]
Hmm, allerdings lassen sich dann nicht alle Vorgänge ermitteln, die sich seit einem spez. Zeitpunkt geändert haben und machen damit den Abgleich mit einem externen System unnötig kompliziert ... ich kann ja nicht bei jedem Abgleich mit einem externen System ALLE Vorgänge abfragen und dann jeden Vorgang syncen, das ist doch performancetechnisch der Overkill ... deshalb wird ein Zeitstempel mit zugehöriger Abfrage benötigt, der wirklich JEDE Änderung an den Daten reflektiert!   

Bitte das Issue wieder öffnen!

**Comment by ic-hv** [comment]
Hmm, ok wenn ichs mir recht überlege ... würde das wohl doch gehen ... OK - Issue kann geschlossen bleiben ;)

**Comment by ptrsauer** [comment]
Es gibt noch andere Stimmen, welche das gleiche Requirement ausdrücken. Daher öffne ich dieses Issue erstmal wieder.

**Comment by ic-hv** [comment]
Mir ist eine Diskrepanz aufgefallen (siehe hierzu folgenden Screenshot):

![vorgangvsvorgaengeabfrage](https://user-images.githubusercontent.com/26538616/26871928-1c3f5550-4b75-11e7-990a-403eac66084a.png)

In der Variable "vorgang" steht ein Vorgang, den ich via GET ausglesen habe, darunter unter "vorgaenge" sind Vorgaenge, die ich via Zeitstempel mittels getVorgaenge ausgelesen habe.

Es ist zu sehen, das die Felder letztesEreignis beim gleichen Vorgang unterschiedliche DateTimes anzeigen ...

**Comment by ptrsauer** [comment]
Ok, letzteres ist ein Bug. Die beiden Zeitangaben sollten schon konsistent sein.

**Comment by ptrsauer** [comment]
Bezüglich der inkonsistenten Zeitangaben des letzten Ereignisses: Ich konnte die Ursache dazu lokalisieren und habe dazu auch einen Fix eingespielt. Bei neuen Ereignissen werden jetzt auch die Daten der Übersicht, welche unter /vorgaenge erscheinen, aktualisiert. Der Fix greift jetzt erstmal nur für neue Ereignisse. Um die Konsistenz der Zeitangaben für alle Vorgänge herzustellen, muss der entsprechende Datastore neu gefeeded werden. Das werde ich heute Abend anstoßen und dann sollte das Problem behoben sein.

Den Zeitstempel der letzten Änderung, also unabhängig von der Erzeugung eines Ereignisses, habe ich jetzt noch nicht eingebaut. Da müssen wir noch mal drauf rum denken.

**Comment by ptrsauer** [comment]
So, ich konnte endlich den entsprechenden DataStore korrekt fluten und jetzt sollten die Zeitangaben bezüglich des letzten Ereignisses korrekt sein.

**Comment by ic-hv** [comment]
Ja, schaut gut aus :)

**Comment by ic-hv** [comment]
Muss ich leider doch wieder öffen, da es mir immernoch wichtig wäre, das jegliche Aenderung der Daten einen Einfluss auf die Ergebnisse hat, die ich via getVorgaenge in Verbindung mit dem aenderungSeit-Parameter erhalte.

**Comment by ic-hv** [comment]
Wie ist der Stand hierzu? Ich hatte vor kurzem auch im Europace Slack-Channel das Thema nochmal angeschnitten, allerdings wurde nicht (mehr) darauf reagiert.

https://europace.slack.com/conversation/C31TS2CMN/p1515685604000855

Dem Kunden (ACCEDO) ist das Thema sehr wichtig ...

**Comment by ollio** [comment]
Hier gehts dazu weiter: https://github.com/hypoport/europace2-api/issues/29

**Comment by ic-hv** [comment]
Da das Thema jetzt wohl in https://github.com/hypoport/europace2-api/issues/29 abgehandelt wird, kann dieser Thread geschlossen werden ...
