### ISSUE TITLE
getVorgaenge: "Internal Server Error" ab page 100 bei limit 100

### ISSUE THREAD

**Issue by ic-hv** [hypoport/europace2-api#17]
Es scheint so, als ob es ein Problem gäbe sobald mittels getVorgaenge die 100-ste Page mit einem Limit von 100 abgerufen wird:

Verwendete Abfrage-Url:
https://baufismart.api.europace.de/v1/vorgaenge?datenKontext=ECHT_GESCHAEFT&limit=100&page=100

Das Resultat:
![servererror](https://user-images.githubusercontent.com/26538616/26932701-9765323c-4c64-11e7-903a-8b90a73f0bca.png)

Bei der Abfrage-Url:
https://baufismart.api.europace.de/v1/vorgaenge?datenKontext=ECHT_GESCHAEFT&limit=100&page=99
erhalte ich noch ein vernünftiges Resultat:

![allright](https://user-images.githubusercontent.com/26538616/26964875-b6e94f64-4cf3-11e7-8a74-4c86098a4c9b.png)

**Comment by ic-hv** [comment]
Lässt sich das Problem auf Europace-Seite nachvollziehen? Wäre nett, wenn Sie hierfür noch eine Lösung finden könnten ...

**Comment by ptrsauer** [comment]
Ja, ich schaue gleich mal rein.

**Comment by ptrsauer** [comment]
Der Fehler ist jetzt behoben. Falls nicht, bitte dieses Issue erneut öffnen.

**Comment by ic-hv** [comment]
Nun ja, das Problem ist leider nur teilweise behoben - ich krieg jetzt zwar keinen 500-er Internal Error mehr, dafür allerdings auch keinerlei Ergebnisse:

![noresults](https://user-images.githubusercontent.com/26538616/27222725-bbe4bba8-528d-11e7-8591-d3f5e1088234.png)

Es sind auf den Pages >= 100 aber definitiv noch Vorgaenge vorhanden ...

![lastsuccesfulcall](https://user-images.githubusercontent.com/26538616/27222932-9f9b1478-528e-11e7-8992-a49e1ab89154.png)

**Comment by ptrsauer** [comment]
Alles klar, dann muss ich da noch mal genauer rein schauen.

**Comment by ptrsauer** [comment]
Ich konnte hier jetzt tiefer eintauchen. Im Backend wird zum schnellen Finden der relevanten Vorgänge Elastic Search verwendet. Unsere Indices sind so eingestellt, dass sie keine Result-Sets mit mehr als 10.000 Ergebnissen ausliefern, da dies zu sehr hohem Speicherkonsum führen kann.

Ein Workaround bei der Nutzung der Vorgänge API wäre es, mit dem Query-Parameter 'aenderungSeit' das Result-Set kleiner zu halten.

Wir könnten auch die Sortierung der Ergebnisse umkehren, so dass die neusten Vorgänge zuerst ausgeliefert werden. Dann hätte man ohne Weiteres erstmal schnellen Zugriff auf die 10000 neusten Vorgänge und könnte über weitere Query-Parameter das Result-Set so einschränken, dass man auch Zugriff auf ältere Vorgänge erhält.

Würde das weiter helfen?

**Comment by ic-hv** [comment]
Ist nicht nötig - ich konnte mir anderweitig behelfen.

Ein Problem besteht allerdings noch: Die folgenden zwei Vorgänge lassen sich nicht via API abrufen, ich erhalte wiederum einen Internal Server Error als Anwort - die Vorgänge haben die EP2-IDs "CL4453" bzw. "486143"

**Comment by ic-hv** [comment]
Hallo, wie ist denn der Stand bzgl. des Auslesens der beiden genannten Vorgänge? Ich erhalte immernoch einen 500-er als Antwort ...

**Comment by ollio** [comment]
Hallo,

Ja wir arbeiten grade an einer besseren Fehlerbehandlung. Da es sich jedoch beim Vorgang auslesen um einen internen Fehler handelt und Sie vermutlich nichts tun können um die Vorgänge zu lesen, schaue ich gleich mal ins Log. 

Habe für beide eine NPE gefunden und schau mir das gleich mal an.
