### ISSUE TITLE
Daten des Haushaltsüberschuss mit ausgeben

### ISSUE THREAD

**Issue by hanack** [hypoport/europace2-api#19]
An jedem Darlehen ist vom Produktanbieter ermittelt der Haushaltsüberschuss gespeichert. Diesen benötigen wir auch in der API.
In der DB zu finden unter
bonitaetsUebersicht in den Angeboten

**Comment by ptrsauer** [comment]
Ältere Angebote haben das Feld 'bonitaetsUebersicht' in der DB. Neuere Angebote haben hier eine Liste von 'bonitaetesUebersichten'.

Ich habe Bitex jetzt entsprechend erweitert und werde morgen die Anträge API entsprechend anpassen.

**Comment by ptrsauer** [comment]
<img width="435" alt="bildschirmfoto 2017-07-03 um 22 37 27" src="https://user-images.githubusercontent.com/13761565/27807337-8d019d90-6040-11e7-8206-1e6edf386c22.png">

Die Bonitätsübersichten werden jetzt unter dem Angebot mit raus gerendert. Die aktualisierte Swagger-Spec lade ich später hoch, wenn die restlichen Änderungen durch sind.

**Comment by ptrsauer** [comment]
Der Knoten heißt jetzt bonitaet und nicht mehr bonitaetsUebersichten.
