### ISSUE TITLE
getVorgang - 500er Fehler bei fehlendem Tilgungssatz

### ISSUE THREAD

**Issue by ic-hv** [hypoport/europace2-api#21]
Beim Abrufen einzelner Vorgänge erhalte ich bei einigen Datensätzen als Antwort den Fehler - "500 kein anderer Tilgungssatz bei Auswahl ANDERER_TILGUNGS_SATZ". 
Das liegt wohl daran, das der Vorgangsbearbeiter ein Setting der folgenden Art gemacht hat:

![fehlendertilgungssatz](https://user-images.githubusercontent.com/26538616/27956986-81597088-631c-11e7-9901-1be75c6ac50e.png)

Da die Mitarbeiter unseres Kunden ein derartiges Setting öfters mal vornehmen, wenn noch nicht konkret gesagt werden kann, welcher Tilgungssatz erwünscht ist, wäre es ratsam das betreffende Feld via API einfach nicht mit auszuliefern, antatt einen 500er Fehler zu generieren.

**Comment by ptrsauer** [comment]
Ja, ein 500er Fehler ist hier auf jeden Fall nicht angebracht. Vielen Dank für den Hinweis. Wir schauen uns das demnächst mal an.

**Comment by ic-hv** [comment]
Hallo, ist hierfür mittlerweile eine anderweitige Lösung, als ein 500er in Sicht?
