### ISSUE TITLE
Antraege auslesen Parameter

### ISSUE THREAD

**Issue by paleise** [hypoport/europace2-api#24]
Hallo,
wo kann ich denn die möglichen Parameter für das Auslesen der Anträge ersehen? Scheinbar gibt es einen Parameter "aenderungSeit=" ? Beim Auslesen erhalte ich im Result unter anderem die Vorgangsnummer und den Link, könnte da gleich noch der Name des Antragstellers mitgegeben werden?

Ist es angedacht beim Auslesen der Anträge das Ergebnis in einem anderen Format evtl. dem gleichen soap wsdl/xsd wie beim Vorgänge upload zurückzugeben?

Gruß Peter

**Comment by ptrsauer** [comment]
Hallo,

neben dem Parameter `aenderungSeit` gibt es nur noch den Parameter `datenKontext` sowie Parameter zum Steuern der Paginierung. Die vollständige Liste der Parameter ist der swagger.yaml der betreffenden API zu finden. Des Weiteren ist in einigen APIs auch eine Dokumentation in HTML verlinkt, welche ebenfalls die möglichen Query-Parameter auflistet.

Die Vorgänge können zur Zeit  nur im JSON-Format ausgegeben werden. Das Einlesen von Vorgängen soll zukünftig auch über die Vorgänge API erfolgen und damit die alte Vorgang-Import-API ersetzen. Ich hoffe, wir kommen noch dieses Jahr dazu dieses Feature umzusetzen.

Das Datenset in der Ergebnisliste ist bisher absichtlich so schmal gehalten. Die vollen Details erhält man dann, wenn man einem der Links folgt. Wie sähe denn ein Use Case aus, bei dem Angaben wie die Namen der Antragsteller, hilfreich wären?

**Comment by ollio** [comment]
Ist hier noch etwas offen oder können wir das Issue schließen?
