### ISSUE TITLE
Vorgang mit Übernahme von Haushalts- oder Objektdaten auch künftig über Schnittstelle möglich?

### ISSUE THREAD

**Issue by triegmann** [hypoport/europace2-api#25]

**Comment by ollio** [comment]
Wie könnte das denn per API aussehen? Macht es nicht mehr Sinn, dass der Client sich die Teile aus den Daten in den neuen Vorgang kopiert, die er übernehmen möchte?

**Comment by caspii** [comment]
Falls diese Issue noch relevant ist, bitte in diesem Repo erneut öffnen: https://github.com/europace/baufismart-vorgaenge-api
