### ISSUE TITLE
Vorgänge auslesen funktioniert nicht mehr

### ISSUE THREAD

**Issue by fincrm-lharter** [hypoport/europace2-api#26]
@ptrsauer 

Hallo zusammen, wir können plötzlich keine Vorgänge mehr auslesen (Baufismart). Wir erhalten immer die Nachricht: 

'{
    "message": "Internal error"
}'

Die Schnittstelle Vorgänge anlegen funktioniert! Können Sie mir bitte helfen bzw. das Problem schnellstmöglich beheben.

**Comment by ollio** [comment]
Ist das noch offen?

**Comment by ptrsauer** [comment]
Ich denke nicht. Bitte wieder öffnen, wenn doch.
