### ISSUE TITLE
Ereignis-Log via Vorgangs-API ausliefern

### ISSUE THREAD

**Issue by ic-hv** [hypoport/europace2-api#27]
Ich hatte hierzu vor einiger Zeit auch bereits im Europace Slack-Channel eine Anfrage gestellt (https://europace.slack.com/archives/C31TS2CMN/p1499323543608631).

Wird in naher Zukunft auch die Möglichkeit bestehen das Ereignis-Log ebenfalls beim Auslesen des Vorgangs mit auszuliefern? Sollte ja eigentlich kein Problem sein ... gehört ja schließlich genauso zum Vorgang, wie die eigentlichen Vorgangsdaten ...

**Comment by ollio** [comment]
Dieser Request wird Bestandteil der Ereignisse API, die wir auf unserer Roadmap für 2018 haben.

**Comment by caspii** [comment]
Die Ereignisse API hat jetzt ein release candidate :https://github.com/europace/baufismart-ereignisse-api
