### ISSUE TITLE
aenderungSeit liefert das Datum der letzten Änderung am Vorgang

### ISSUE THREAD

**Issue by ollio** [hypoport/europace2-api#29]
*aenderungSeit* berücksichtigt nur das Datum des letzten Ereignis. Eigentlich sollte es das Datum der letzten Änderung am Vorgang berücksichtigen.

Interessenten: ACCEDO, C24

**Comment by ollio** [comment]
Das Datum sollte auf dem Feld letzteAenderung am TV bzw. letztes Ereignis basieren. 
Betroffen ist das Feeden in die Vorgangs-Suche.

**Comment by ic-hv** [comment]
Eine weitere Anmerkung: Es kommt immer mal wieder vor, das einzelne Vorgänge mit dem aenderungSeit Parameter nicht erwischt werden, weil diese wohl noch nicht in die Vorgangs-Suche "gefeedet" wurden.

Es stellt sich mir deshalb die Frage, wie lange es im Höchstfall dauern kann, bis ein Fall mit einer relevanten Änderung in die Vorgangs-Suche gefeedet wird.

**Comment by ollio** [comment]
Zum Abrufen der Vorgänge, an dem sich etwas geändert hat, sollte das Datum letzteAenderung vom Vorgang via API ausgegeben werden und auch eine Sortierung angeboten werden.

STARPOOL

**Comment by ollio** [comment]
Datums-Feld letzteAenderung in Vorgang-Modell aufnehmen

**Comment by ollio** [comment]
https://github.com/hypoport/vorgaenge-api/releases/tag/v2.2
