### ISSUE TITLE
TippgeberPartnerId fehlt in europace2-api/BaufiSmart/vorgang-anlegen/v12/

### ISSUE THREAD

**Issue by jenskabella** [hypoport/europace2-api#3]
Hallo,
wir haben vor kurzem die europace2-api/BaufiSmart/vorgang-anlegen/ von v10 auf die v12 angehoben.

Wir vermissen nun die TippgeberPartnerId. Den Tippgeber finde ich nur in den VorgangMetadaten, die ich als Response des Request erhalte. Wie können wir in der v12 den Tippgeber an BaufiSmart übergeben?

**Comment by gruenewa** [comment]
Hallo,

ein Bugfix läuft durch unsere Deploymentpipline und sollte noch heute produktiv gehen.
