### ISSUE TITLE
Beim Login werden keine Passwörter, die ein + enthalten akzeptiert.

### ISSUE THREAD

**Issue by ollio** [hypoport/europace2-api#31]
Bei der Weiterleitung zum Partnermanagement wird das PW nicht korrekt escaped.

**Comment by caspii** [comment]
Hier eine Aussage von einem betroffenen Nutzer
> Authentifizierung mit API Key: das ist nicht realisierbar, kann nicht für ALLE meine Untervermittler den API Key beantragen. Es wurde mir so auch empfohlen.

Siehe https://europace.slack.com/archives/C31TS2CMN/p1540225851000100

**Comment by Atrusberlin** [comment]
@caspii mit einem Test via Postman hat die Basic-Authentifizierung mit einem Password inkl. `+` funktioniert. Die Vermutung ist, dass hier das Login mittels der Urlparameter ausgeführt wird, ohne die Daten zu escapen. Womöglich eine Fehlnutzung beim Client?

**Comment by paleise** [comment]
@Atrusberlin : welche Sonderzeichen bei der ersten Anfrage im Passwort waren, kann ich jetzt nicht mehr nachvollziehen. Dieses mal war ein # am Ende des Pw's und hier erhielt ich definitiv kein Token zurück. User hat sein pw geändert, jetzt ohne # und es funktioniert. Gleiche App ==> eher keine Fehlnutzung.

**Comment by caspii** [comment]
@paleise mein Kollege meint den API Client. Nutzen sie den generierten Client?

**Comment by paleise** [comment]
ja, login über die URL. Jedoch mittels POST Methode, da sollte das escapen eigentlich nicht erforderlich sein, also mal ganz einfach:
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(credentialUrl);
            string postdata = "username=" + username + "&password=" + password;
            var data = Encoding.ASCII.GetBytes(postdata);
            request.Method = "POST";
            request.ContentType = "application/x-www-form-urlencoded";
            using (var stream1 = request.GetRequestStream())
            {
                stream1.Write(data, 0, data.Length);
            }
           var response = (HttpWebResponse) request.GetResponse();

Ich habe das jetzt einmal durchgetestet: ein # am im Passwort geht, ein + nicht. Evtl. war bei der letzten Anfrage noch ein + innerhabl des Pw's

**Comment by paleise** [comment]
@all ist mir wieder passiert, login über webRequest mit einem Passwort das ein Sonderzeichen am Ende beinhaltet (ich kann leider schlecht den Anwender nach seinem PW bei Europace fragen, darum ist mir leider das Sonderzeichen nicht bekannt) schlägt fehl. Er hat es (das PW) dann abgeändert ==> funktioniert... ist aber nicht gerade wirklich gut...

**Comment by caspii** [comment]
@paleise danke für die Meldung. Wir schauen uns das noch mal an

**Comment by caspii** [comment]
@Atrusberlin Ich kann das gemeldete Verhalten nachvollziehen. Ich habe es mit curl getestet:
`curl -v --insecure --header "Content-type: application/x-www-form-urlencoded;charset=UTF-8" --data "username=Mustermann@beispiel.de&password=4711" https://www.europace2.de/partnermanagement/login.do`

Wenn ein `!` innerhalb des Passworts vorkommt, klappt die Anmeldung
Wenn ein `+` innerhalb des Passworts vorkommt, klappt die Anmeldung *nicht*

**Comment by caspii** [comment]
@paleise Nachdem ich das Passwort richtig kodiert hatte, klappe es dann auch mit einem `+`im Passwort. Da `+`ein Sonderzeichen in URLs ist, muss es kodiert werden. 

Die Login API funktioniert also korrekt in dieser Hinsicht. Versuchen sie also die richtige `urlencode` Methode anzuwenden.
