### ISSUE TITLE
InvestitionsObjekt Haus - Gewerbefläche wird nicht übernommen

### ISSUE THREAD

**Issue by tomuench** [hypoport/europace2-api#36]
Hallo zusammen,
ich versuche die Felder gewerbeflaecheVorhanden und gesamtGewerbeflaeche and der Entität Haus zu übertragen. Die Schnittstelle akzeptiert meine übersendeten Informationen, jedoch werden die erwarteten Felder im Europace-Portal nicht gefüllt.

Ausschnitt XML:
```xml
<haus>
...
<wohnflaecheGesamt>100.0</wohnflaecheGesamt>
<gewerbeflaecheVorhanden>true</gewerbeflaecheVorhanden>
<gesamtGewerbeflaeche>100.0</gesamtGewerbeflaeche>
...
</haus>
 ```
Screenshot: 
![image](https://user-images.githubusercontent.com/4034506/46856854-dba64500-ce07-11e8-9ffa-cd9849ae8e04.png)

Ist es ein Bug oder kann mir jemand einen Hinweis geben woran es liegt?

**Comment by gruenewa** [comment]
Hallo, 

ich vermute es ist ein Bug. Wir prüfen das.

**Comment by gruenewa** [comment]
Hallo, 

wir haben den Fehler jetzt behoben. 
Danke nochmal für den Hinweis.
