### ISSUE TITLE
BEX: Einzusetzendes Vermögen + Gar nicht

### ISSUE THREAD

**Issue by tomuench** [hypoport/europace2-api#38]
Moin zusammen,

ich möchte gerne bei einzusetzendes Vermögen "Gar nicht" hinterlegen können. In der Benutzeroberfläche von Europace ist es unter "Einzusetzendes Vermögen Haushalt 1" vorhanden, jedoch in der Schnittstelle nicht möglich, siehe unten.

Screenshot GUI

![einzusetzendes_vermoegen](https://user-images.githubusercontent.com/4034506/47219134-3adafb00-d3ae-11e8-98f0-124dd15d9c7c.png)

Wäre es möglich GAR_NICHT in diesen Enum einzufügen?

Viele Grüße!

```
<xs:simpleType name="VermoegensEinsatz">
  <xs:restriction base="xs:string">
<xs:enumeration value="ABTRETEN"/>
<xs:enumeration value="AUFLOESEN"/>
  </xs:restriction>
</xs:simpleType>```

**Comment by gruenewa** [comment]
Ich nehme das mal mit ins Team zur Prüfung. Kann aber noch nicht sagen, ob wir das zeitnah umsetzen können/wollen. Eventuell können wir die Erweiterung  in das nächste BEX Release einarbeiten.

**Comment by caspii** [comment]
@gruenewa das wurde Doch heute im Standup besprochen. Was war die Entscheidung?

**Comment by caspii** [comment]
Hallo @tomuench. Können sie evtl. das Vermögen ganz weglassen? Wir wollen diese API noch ungerne erweitern, sondern lieber den REST Nachgänger liefern

**Comment by gruenewa** [comment]
@caspii Wir hatten den Verdacht geäußert, dass man das Feld *vermoegensEinsatz* einfach auslassen könnte und der Importer diese dann in BaufiSmart auf *gar nicht* mappt. Es handelt sich aber um ein Pflichtfeld und es gibt einen Validierungsfehler, wenn man das Feld weglässt. Eine Alternative wäre beim Import den gesamten Block *vermögensVerwendung* auszulassen. Das funktioniert zwar, aber die Information, dass das Vermögen nicht abgelöst werden soll, geht verloren. Aktuell lässt sich das leider nicht in BEX abbilden. Wir bräuchten eine Erweiterung der API. Das geht dann aber nur mit einem neuen Release.

**Comment by tomuench** [comment]
@caspii das Vorgehen wäre für mich in Ordnung. Sie sprache ein REST-Nachfolger an. Wann wäre das release geplant?

**Comment by caspii** [comment]
@tomuench OK, super.

Der REST Nachfolger ist momentan für 2019 Q3 oder Q4 geplant. Dauert also noch etwas...

**Comment by tomuench** [comment]
Das führt mich zu einer weiteren Frage, @caspii 
Da RESTful-Webservices eingeführt werden, werden irgendwann die SOAP-Webservices eingestellt bzw. ist das schon geplant?

**Comment by caspii** [comment]
Ja, perspektivischen werden die SOAP SSTs eingestellt werden, das ist aber nicht weit entfernt. Das werden wir selbstverständlich frühzeitig mit vielen Monaten Vorlauf kommunizieren.

**Comment by tomuench** [comment]
Ich akzeptiere @caspii Lösung. Es sollten keine Werte übertragen werden, wenn der Status "Gar nicht" erreicht werden soll

**Comment by caspii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BEX API Erweiterung](https://trello.com/c/GUeUcs8K/107-bex-api-erweiterung)
