### ISSUE TITLE
Baufismart + Gewerbefläche Teil_vermietet

### ISSUE THREAD

**Issue by tomuench** [hypoport/europace2-api#39]
Moin Zusammen,

habe wieder etwas gefunden, was auf einen Bug schließen lässt. Ich übertrage ein Objekt mit Gewerbefläche und Teilvermietung, jedoch kommen zwei Aspekte nicht im Europace-Objekt an:

- gewerbeNutzungsArt
- gewerbeVermietungsInformation

Übertragen wurden folgende Informationen:

```xml
<haus>
...
<gewerbeflaecheVorhanden>true</gewerbeflaecheVorhanden>
<gesamtGewerbeflaeche>251.0</gesamtGewerbeflaeche>
<gewerbeNutzungsArt>TEIL_VERMIETET</gewerbeNutzungsArt>
<gewerbeVermietungsInformation>
  <mieteinnahmenNettoKaltMonatlich>2505.98</mieteinnahmenNettoKaltMonatlich> 
  <vermieteteWohnflaecheBeiTeilvermietung>151.0</vermieteteWohnflaecheBeiTeilvermietung>
</gewerbeVermietungsInformation>
...
</haus>
```

Angekommen in der Oberfläche ist folgendes:

![europace_gewerbeflaeche](https://user-images.githubusercontent.com/4034506/47776948-e0b63000-dcf3-11e8-8cbd-d64f8da94580.png)

Würde mich über Feedback freuen! :smile:

**Comment by gruenewa** [comment]
Hallo,

Danke für den Hinweis. Ich denke, es ist ein Fehler und, dass wir diesen zeitnah beheben können.

**Comment by gruenewa** [comment]
Hallo,

wir haben den Fehler behoben. Der Import der Gewerbe Vermietungsinformation funktioniert wieder. Danke nochmal für den Hinweis. :+1:
