### ISSUE TITLE
Übergeordnete EP2-PartnerID zurückgeben

### ISSUE THREAD

**Issue by ic-hv** [hypoport/europace2-api#6]
Bei den Partner-Daten, die via PEX-API abgefragt werden können, wäre es sinnvoll, ein Feld auszuliefern, das angibt welcher Europace-ID der Partner direkt untergeordnet ist. Beim Anlegevorgang kann man diese Information ja mitgeben - entsprechend sinnvoll wäre es, wenn man sie auch wieder auslesen könnte.

**Comment by Atrusberlin** [comment]
Vielen Dank für den Hinweis, wir prüfen die Anforderung.

**Comment by Madensucher** [comment]
'Parent als HAL Ressource beim Partnerabruf' wäre ausreichend, wenn dabei der komplette Baum von der eigenen Plakette bis zur Wurzel ausgegeben wird. Nur die direkt übergeordnete Plakette löst das Problem nicht.

**Comment by ic-hv** [comment]
Wie steht es um diese Anforderung? Ein Feld "vertriebsOrganisation" das die direkt übergeordnete Vertriebsorganisation enthält, würde (mir) schon helfen ...

**Comment by caspii** [comment]
Duplicate von https://github.com/europace/partner-api/issues/1
