### ISSUE TITLE
Pfad der übergeordeneten EP2-PartnerIds zurückgeben

### ISSUE THREAD

**Issue by Madensucher** [hypoport/europace2-api#8]
Es gibt Anwendungsfälle, in denen die Zuordnung eines Vorgangs zu einer Plakette (das ist nicht immer die direkt übergeordnete Plakette) geprüft werden muß.

Beispiel: 
- alle Vorgänge meiner Vetriebseinheit/meiner übergeordnete Vertriebseinheit

Aktuell ist das Problem nur zu lösen, wenn man zusätzlich die partner.csv einliest und sich die Struktur der Plakette aufbaut.

**Comment by ollio** [comment]
Das ist ein interessanter Fall für die Partner Api. Meinst du die Übergeordneten Partner im Baum?
Ich könnte mir vorstellen, dass wir den Parent als HAL Ressource beim Partnerabruf herauszugeben.
Würde das Dein Problem lösen?

**Comment by ollio** [comment]
https://github.com/hypoport/europace2-api/issues/6

**Comment by caspii** [comment]
https://github.com/europace/partner-api/issues/1
