### ISSUE TITLE
Class 'Gebaeude' inkompatibel

### ISSUE THREAD

**Issue by isk0001y** [hypoport/europace2-api#9]
Hallo,

Während API die Felder 'anzahlVollgeschosse' und 'anzahlDerWohneinheitenImGebaeude' vorsieht, schickt die Mock-Schnittstelle 'anzahlGeschosse' und 'anzahlDerWohneinheitenImObjekt'.

Das verwirrt einen potenziellen Mapper.

Viele Grüße

**Comment by ptrsauer** [comment]
Das ist definitiv ein Fehler. Wir werden das beheben.

**Comment by ptrsauer** [comment]
Ich habe die Mock-Daten jetzt entsprechend angepasst. Vielen Dank für den Hinweis!
